### PR TITLE
feat: narrow UX for exploring open-sauced gql

### LINKED ISSUE #1: Feature: Select Queries
### Is your feature request related to a problem? Please describe.

As discussed in discord, may be good to have ability to choose queries (at least from the dynamic list).

### Describe the solution you'd like

Dropdown to choose from queries, ability to edit and run query.
May be good to disable explorer altogether.

### Additional context

There are concerns of usability with just the explorer enabled.

### PR DESCRIPTION
**Pull request by mtfoley**
## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [x] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds a select element with options for each of the dynamic queries/mutations used in OpenSauced. Choosing a query/mutation populates the code editor and the explorer. This PR also modifies the schema returned from OneGraph prior to populating the explorer on the left side so that the schema portions are limited to those for GitHub and OneGraph. The expressions that are mutations are automatically reflected as such in their option labels.

## Related Tickets & Documents

Fixes #1 

## Mobile & Desktop Screenshots/Recordings
Screen Shot 2021-07-22 at 11 33 50 PM

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 docs
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
sorta

### CODE REVIEW

**Comment by 0-vortex** [comment]
holy s^% that was fast, didn't even get to copy the labels 🔥

**Comment by mtfoley** [comment]
@mtfoley @bdougie I think I've got this just about right now!

I spent like 3.5 hours trying to filter the schema results the wrong way (inclusive build up, chasing down dependencies), and then another 1 hour trying it what looks like the right way (surgically remove things that are the types we don't want, strip those out of other types' field lists, and then purging out types that are no longer valid).

Also the `operationName` prop on the GraphiQL components seems to sync well.

**Comment by 0-vortex** [comment]
couple bits of code went missing but everything works with some HUGE extras 🔥 

thanks @mtfoley you are forever in my mind 🥇

**Comment by mtfoley** [comment]
I enjoyed this one! I'll clean up those missing bits (eg toolbar buttons) and move on to docs and the other todos in this PR.

**Comment by mtfoley** [comment]
here's what I was thinking of adding to the readme:

## 🧪 Built for Experimenting

This tool is meant to accelerate development on [Open Sauced](https://opensauced.pizza) by giving contributors a way to explorer GraphQL queries/mutations and results in an interactive way. It is similar to most implementations of GraphiQL, except that it features dropdown menus to select from the various dynamic queries in use by [Open Sauced](https://opensauced.pizza), described in [https://docs.opensauced.pizza/contributing/fetching-data-from-github/](https://docs.opensauced.pizza/contributing/fetching-data-from-github/).

**Review by mtfoley — COMMENTED** [review]
Done reviewing for now, wish this thing would close

**Pull request merged**
